"""Add logged_in column to users

Revision ID: 9a9317772a5d
Revises: e5a5ad259ffd
Create Date: 2025-03-09 19:02:50.170526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9317772a5d'
down_revision = 'e5a5ad259ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logged_in', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('logged_in')

    # ### end Alembic commands ###
