"""changed the transaction model types from income & expense to received & sent

Revision ID: e65886c90b0c
Revises: 34e253bea389
Create Date: 2025-03-08 07:26:54.420344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e65886c90b0c'
down_revision = '34e253bea389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('received', 'sent', name='transaction_type'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('received', 'sent', name='transaction_type'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###